version: "3.8"
   
services:
  book:
    image: book-py:test   # docker build . -t book-py:test
    container_name: book
    environment:
      DJANGO_SECRET_KEY: django-insecure-f_b9+t*hxq2%qwf8^o%inh!#!u78*jb$$4ss%6j73j$$yjk7tuw8
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: pgdb_book
      DATABASE_PORT: 5432
      POSITION: compose
    ports:
      - "8000:8000"
    depends_on:
      - pgdb_book

  pgdb_book:
    image: postgres:latest
    container_name: pgdb_book
    ports:
      - "5432:5432"
    command: docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200'
    volumes:
      - postgres_data_book:/var/lib/postgresql/data
      - ./api/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
            
  customer:
    image: customer-py:test   # docker build . -t customer-py:test
    container_name: customer
    environment:
      DJANGO_SECRET_KEY: django-insecure-&s3d*_rfyrke=lf)y3psfd(($$4321a*ft%%gdy+@hjcr6hwvh1
      DATABASE_NAME: customer_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 27017
    command: python microservices_customer/manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"

  borrowing:
    image: borrowing-py:test   # docker build . -t borrowing-py:test
    container_name: borrowing
    environment:
      DJANGO_SECRET_KEY: django-insecure-*rb0)os_c$$5ec-3+$$6nnnw3whswq(mkjeptbsrwhg8%w(1i#ml
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: pgdb_borrowing
      DATABASE_PORT: 5432
      HOST_BOOK: book
      HOST_CUSTOMER: customer
      PORT_BOOK: 8000          
      PORT_CUSTOMER: 8000
    command: python microservices_borrowing/manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    depends_on:
      - pgdb_borrowing
      - book
      - customer

  pgdb_borrowing:
    image: postgres:latest
    container_name: pgdb_borrowing
    ports:
      - "5433:5432"
    command: docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200'
    volumes:
      - postgres_data_borrowing:/var/lib/postgresql/data
      - ./microservices_borrowing/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  postgres_data_book: {}
  postgres_data_borrowing: {}
