---
fullnameOverride: borrowing-postgres
global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
initdbUser: postgres
initdbPassword: postgres
initdbScripts:
  dbinit.sql: |
    CREATE DATABASE "borrowing" OWNER postgres;
    \connect borrowing
    ALTER DATABASE "borrowing" SET TIMEZONE TO 'Europe/Rome';
    SET TIMEZONE TO 'Europe/Rome';

    CREATE TABLE "borrowing"
    (
    id integer,
    id_book integer,
    id_cutomer integer
    ) TABLESPACE pg_default;

    ALTER TABLE "borrowing"
        OWNER to postgres;

  
