---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-ms
          image: giovannicafasso/notification:1.1-SNAPSHOT
          ports:
          - containerPort: 10000
          imagePullPolicy: Always
