---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-ms
          image: giovannicafasso/customer:1.0-SNAPSHOT
          envFrom:
          - configMapRef:
              name: customer-config
          ports:
          - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32103
      port: 8000
      targetPort: 8000
  selector:
    app: customer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGLEVEL: "info"
  DEBUG: "True"
  DATABASE_ENGINE: "djongo"
  DJANGO_SECRET_KEY: "django-insecure-&s3d*_rfyrke=lf)y3psfd(($4321a*ft%%gdy+@hjcr6hwvh1"
  DATABASE_NAME: "customer_db"
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "root"
  DATABASE_PORT: "27017"