---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book-ms
          image: giovannicafasso/book:1.3-SNAPSHOT
          envFrom:
          - configMapRef:
              name: book-config
          ports:
          - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32102
      port: 8000
      targetPort: 8000
  selector:
    app: book
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGLEVEL: "info"
  DEBUG: "True"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DJANGO_SECRET_KEY: "django-insecure-f_b9+t*hxq2%qwf8^o%inh!#!u78*jb$4ss%6j73j$yjk7tuw8"
  DATABASE_NAME: "postgres"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "postgres"
  DATABASE_HOST: "pgdb_book"
  DATABASE_PORT: "5432"